version: '3'
services:
#  redis:
#    image: "redis:alpine"
#    container_name: redis
#    ports:
#      - "6379:6379"

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
#    environment:
#      SPRING_REDIS_HOST: redis  # Redis service name for communication
#      SPRING_REDIS_PORT: 6379
#    depends_on:
#      - redis